Repository koreatech/hanpyo, pull requests merged in 2021-04, with the labels that each got.

#39 커스텀 Typography 제거
  client/src/components/UI/atoms/HeaderMenu/HeaderMenu.tsx
  client/src/components/UI/atoms/LectureInfoTitle/LectureInfoTitle.tsx
  client/src/components/UI/atoms/Typography/Typography.stories.tsx
  client/src/components/UI/atoms/Typography/Typography.tsx
  client/src/components/UI/atoms/index.ts
  client/src/components/UI/molecules/HeaderAuthSection/HeaderAuthSection.tsx
  client/src/components/UI/molecules/Timetable/SelectTab/Menus/Menus.tsx
  client/src/components/UI/molecules/Timetable/SelectTab/Menus/Modal.tsx
  client/src/components/UI/molecules/Timetable/SelectTab/SelectTab.stories.tsx
  client/src/components/UI/molecules/Timetable/SelectTab/SelectTab.tsx
  client/src/components/UI/molecules/index.ts
  client/src/components/UI/organisms/Header/Header.tsx
Labels: 🎨 FE, 🚧 Refactor, 🧍‍♂️ atom

#41 폰트 적용
  client/src/common/styles/theme.ts
  client/src/fonts/AppleSDGothicNeoB.ttf
  client/src/fonts/AppleSDGothicNeoEB.ttf
  client/src/fonts/AppleSDGothicNeoH.ttf
  client/src/fonts/AppleSDGothicNeoL.ttf
  client/src/fonts/AppleSDGothicNeoM.ttf
  client/src/index.css
  client/src/index.tsx
Labels: 🎨 FE

#45 강의 정보 시간 UI 수정
  client/src/components/UI/atoms/LectureInfoTitle/LectureInfoTitle.tsx
  client/src/components/UI/molecules/LectureInfo/LectureInfo.tsx
Labels: 🎨 FE, 🚧 Refactor

#49 로그인 모달 작업
  client/src/components/UI/molecules/HeaderAuthSection/HeaderAuthSection.tsx
  client/src/components/UI/molecules/HeaderAuthSection/HeaderAuthSectionArea.tsx
  client/src/components/UI/molecules/LoginModalContent/LoginModalContent.stories.tsx
  client/src/components/UI/molecules/LoginModalContent/LoginModalContent.tsx
  client/src/components/UI/molecules/TimeTableModalContent/TimeTableModalContent.tsx
  client/src/components/UI/molecules/index.ts
  client/src/components/UI/organisms/ModalPopup/LoginModalPopup.stories.tsx
  client/src/components/UI/organisms/ModalPopup/LoginModalPopup.tsx
  client/src/components/UI/organisms/ModalPopup/ModalPopup.tsx
  client/src/components/UI/organisms/index.ts
  client/src/stores/ModalStore.ts
Labels: 🎨 FE, 👨‍👨‍👦 organism, 👭 molecule

#52 SelectMenu 컴포넌트 제작
  client/.eslintrc.js
  client/.storybook/preview.js
  client/src/__test__/common/utils/range.test.ts
  client/src/__test__/common/utils/testcalc.test.ts
  client/src/common/utils/index.ts
  client/src/common/utils/range.ts
  client/src/common/utils/scroll.ts
  client/src/common/utils/testcalc.ts
  client/src/components/UI/atoms/Button/Button.tsx
  client/src/components/UI/atoms/SelectMenu/SelectMenu.stories.tsx
  client/src/components/UI/atoms/SelectMenu/SelectMenu.tsx
  client/src/components/UI/atoms/TimeSelectMenu/TimeSelectMenu.stories.tsx
  client/src/components/UI/atoms/TimeSelectMenu/TimeSelectMenu.tsx
  client/src/components/UI/atoms/index.ts
  client/src/components/UI/molecules/LectureSearchFilter/LectureSearchFilter.stories.tsx
  client/src/components/UI/molecules/LectureSearchFilter/LectureSearchFilter.tsx
  client/src/components/UI/molecules/LectureSearchFilter/LectureSearchFilterMenu.tsx
  client/src/components/UI/molecules/TimeTableAddForm/TimeTableAddForm.tsx
  client/src/components/UI/molecules/TimeTableAddForm/TimeTableAddFormContent.stories.tsx
  client/src/components/UI/molecules/TimeTableAddForm/TimeTableAddFormContent.tsx
  client/src/components/UI/molecules/index.ts
  client/src/components/UI/organisms/Header/Header.tsx
  client/src/components/pages/MainPage.tsx
Labels: 👨‍👨‍👦 organism, 🧍‍♂️ atom

#56 스토리북 코드 컨벤션 수정
  client/src/components/UI/atoms/Button/Button.stories.tsx
  client/src/components/UI/atoms/HeaderMenu/HeaderMenu.stories.tsx
  client/src/components/UI/atoms/LectureGrid/LectureGrid.stories.tsx
  client/src/components/UI/molecules/HeaderAuthSection/HeaderAuthSection.stories.tsx
  client/src/components/UI/molecules/LoginModalContent/LoginModalContent.stories.tsx
  client/src/components/UI/molecules/ModalPopupArea/ModalPopupArea.stories.tsx
  client/src/components/UI/molecules/Notice/Notice.stories.tsx
  client/src/components/UI/molecules/SearchBar/SearchBar.stories.tsx
  client/src/components/UI/molecules/SubTitle/SubTitle.stories.tsx
  client/src/components/UI/molecules/TimeTableModalContent/TimeTableModalContent.stories.tsx
  client/src/components/UI/molecules/TimeTableTabBtnGroup/TimeTableTabBtnGroup.stories.tsx
  client/src/components/UI/molecules/TimeTableTabMenu/TimeTableTabMenu.stories.tsx
  client/src/components/UI/molecules/Timetable/Timetable.stories.tsx
  client/src/components/UI/organisms/Header/Header.stories.tsx
  client/src/components/UI/organisms/LectureList/LectureList.stories.tsx
  client/src/components/UI/organisms/ModalPopup/LoginModalPopup.stories.tsx
  client/src/components/UI/organisms/ModalPopup/TimeTableModalPopup.stories.tsx
  client/src/components/UI/organisms/TimeTableMenu/TimeTableMenuArea.stories.tsx
Labels: 🎨 FE, 🚧 Refactor

#57 eslint 불필요한 옵션 off 작업
  client/.eslintrc.js
  client/src/components/UI/atoms/AlertSnackbar/AlertSnackbar.tsx
  client/src/components/UI/atoms/SelectMenu/SelectMenu.tsx
  client/src/components/UI/atoms/TimeSelectMenu/TimeSelectMenu.tsx
  client/src/components/UI/molecules/SearchBar/SearchBar.tsx
  client/src/components/UI/molecules/SubTitle/SubTitle.tsx
  client/src/components/UI/molecules/TimeTableAddForm/TimeTableAddFormContent.tsx
  client/src/components/UI/molecules/TimeTableTabMenu/TimeTableTabMenu.tsx
Labels: 🎨 FE, 🚧 Refactor

#62 feat: color 랜덤 배정 기능 추가
  client/src/components/UI/molecules/LectureBoxContainer/LectureBoxContainer.tsx
  client/src/components/UI/molecules/LectureInfo/LectureInfo.tsx
  client/src/stores/TimeTableStore.ts
Labels: 🎨 FE, 🚧 Refactor

#64 과목 - 시간표간 인터액션 개선 및 기능 추가
  client/src/apollo.ts
  client/src/components/UI/atoms/SameLectureBox/SameLectureBox.tsx
  client/src/components/UI/atoms/index.ts
  client/src/components/UI/molecules/LectureBoxContainer/LectureBoxContainer.tsx
  client/src/components/UI/molecules/LectureInfo/LectureInfo.tsx
  client/src/components/UI/molecules/LectureListBody/BasketLectureListBody.tsx
  client/src/components/UI/molecules/LectureListBody/SearchedLectureListBody.tsx
  client/src/components/UI/molecules/Timetable/Timetable.tsx
  client/src/components/UI/organisms/LectureList/LectureList.tsx
  client/src/stores/LectureInfoStore.ts
  client/src/stores/RootStore.ts
  client/src/stores/TimeTableStore.ts
  client/src/stores/index.ts
  client/src/stores/timetable.ts
Labels: 🎨 FE, 👭 molecule, 🚧 Refactor

#66 라우팅 작업
  client/src/components/UI/atoms/HeaderMenu/HeaderMenu.tsx
  client/src/components/UI/organisms/Header/Header.tsx
  client/src/components/pages/MyPage.tsx
  client/src/components/pages/ReviewPage.tsx
  client/src/components/pages/index.ts
  client/src/router/Router.tsx
Labels: 🎨 FE, 👨‍👩‍👧‍👦 page

#69 시간표 탭 추가시 입력한 탭 이름으로 추가하도록 코드 추가
  client/src/components/UI/molecules/TimeTableModalContent/TimeTableModalContent.tsx
  client/src/components/UI/organisms/ModalPopup/ModalPopup.tsx
  client/src/components/UI/organisms/ModalPopup/TimeTableModalPopup.tsx
Labels: 🎨 FE

#71 LectureReview View 작업
  client/src/components/UI/atoms/HashTag/HashTag.stories.tsx
  client/src/components/UI/atoms/HashTag/HashTag.tsx
  client/src/components/UI/atoms/LectureReviewRating/LectureReviewRating.stories.tsx
  client/src/components/UI/atoms/LectureReviewRating/LectureReviewRating.tsx
  client/src/components/UI/atoms/ThumbScore/ThumbScore.stories.tsx
  client/src/components/UI/atoms/ThumbScore/ThumbScore.tsx
  client/src/components/UI/atoms/index.ts
  client/src/components/UI/molecules/LectureReviewHashTags/LectureReviewHashTags.stories.tsx
  client/src/components/UI/molecules/LectureReviewHashTags/LectureReviewHashTags.tsx
  client/src/components/UI/molecules/LectureReviewInfo/LectureReviewInfo.stories.tsx
  client/src/components/UI/molecules/LectureReviewInfo/LectureReviewInfo.tsx
  client/src/components/UI/molecules/LectureReviewThumbs/LectureReviewThumbs.stories.tsx
  client/src/components/UI/molecules/LectureReviewThumbs/LectureReviewThumbs.tsx
  client/src/components/UI/molecules/index.ts
  client/src/components/UI/organisms/LectureReview/LectureReview.stories.tsx
  client/src/components/UI/organisms/LectureReview/LectureReview.tsx
  client/src/components/UI/organisms/LectureReview/LectureReviewContainer.tsx
  client/src/components/UI/organisms/index.ts
  client/src/components/pages/ReviewPage.tsx
Labels: 🎨 FE, 👨‍👨‍👦 organism, 👭 molecule, 🧍‍♂️ atom

#72 chore: travis-CI 설정 변경
  .travis.yml
  appspec.yml
  execute-deploy.sh
  server/.eslintrc.js
  server/.prettierrc.js
  server/.vscode/settings.json
  server/package-lock.json
  server/package.json
  server/src/api/hello/hello.graphql
  server/src/api/hello/hello.resolvers.ts
  server/src/app.ts
  server/src/config/schema.ts
  server/src/index.ts
  server/tsconfig.json
Labels: ⚙ Setting, 🎨 FE, 🏕 DevOps

#81 전체 코드 리팩토링
  client/src/common/utils/debounce.ts
  client/src/components/UI/atoms/AlertSnackbar/AlertSnackbar.tsx
  client/src/components/UI/atoms/LectureBox/LectureBox.tsx
  client/src/components/UI/atoms/LectureInfoTitle/LectureInfoTitle.tsx
  client/src/components/UI/atoms/SameLectureBox/SameLectureBox.tsx
  client/src/components/UI/molecules/HeaderAuthSection/HeaderAuthSectionArea.tsx
  client/src/components/UI/molecules/LectureBoxContainer/LectureBoxContainer.tsx
  client/src/components/UI/molecules/LectureInfo/LectureInfo.tsx
  client/src/components/UI/molecules/LectureListBody/SearchedLectureListBody.tsx
  client/src/components/UI/molecules/Timetable/Timetable.tsx
  client/src/components/UI/organisms/LectureList/LectureList.tsx
  client/src/components/UI/organisms/TimeTableMenu/TimeTableMenu.tsx
  client/src/components/pages/MainPage.tsx
  client/src/components/pages/MyPage.tsx
  client/src/components/pages/ReviewPage.tsx
  client/src/router/Router.tsx
Labels: 🎨 FE, 🚧 Refactor

#82 강의리뷰 페이지 뷰 작업강의리뷰 페이지 뷰 작업
  client/src/components/UI/molecules/ReviewSearchSection/ReviewSearchSection.tsx
  client/src/components/UI/molecules/SearchBar/SearchBar.tsx
  client/src/components/UI/molecules/index.ts
  client/src/components/UI/organisms/LectureReview/LectureReview.tsx
  client/src/components/UI/organisms/LectureReview/LectureReviewContainer.tsx
  client/src/components/pages/ReviewPage.tsx
Labels: 🎨 FE, 👨‍👩‍👧‍👦 page

#84 chore: develop branch travis 설정 추가
  .travis.yml
Labels: ⚙ Setting, 🏕 DevOps

#85 JS 타입 체크 모듈 정의
  client/src/__test__/common/utils/typeCheck.test.ts
  client/src/common/utils/index.ts
  client/src/common/utils/typeCheck.ts
  client/src/components/UI/molecules/LectureBoxContainer/LectureBoxContainer.tsx
  client/src/components/UI/molecules/LectureInfo/LectureInfo.tsx
  client/src/components/UI/organisms/LectureList/LectureList.tsx
Labels: 🎨 FE, 🚧 Refactor

#86 Form 데이터 유효성 검사 유틸 모듈 제작
  client/src/__test__/common/utils/validator.test.ts
  client/src/common/utils/validator.ts
  client/src/components/UI/molecules/LoginModalContent/LoginModalContent.tsx
  client/src/components/UI/molecules/SignUpModalContent/SignUpModalContent.tsx
Labels: 🎨 FE, 🚧 Refactor
