Repository koreatech/hanpyo, pull requests merged in 2021-05, with the labels that each got.

#90 강의 리뷰 클릭시 버그 제거 및 기타 등등
  client/public/index.html
  client/src/components/UI/atoms/LectureReviewRating/LectureReviewRating.tsx
  client/src/components/UI/atoms/ThumbScore/ThumbScore.tsx
  client/src/components/UI/molecules/LectureReviewHashTags/LectureReviewHashTags.tsx
  client/src/components/UI/molecules/LectureReviewThumbs/LectureReviewThumbs.tsx
  client/src/components/UI/molecules/ReviewDetailModalContent/ReviewDetailModalContent.tsx
  client/src/components/UI/organisms/Footer/Footer.stories.tsx
  client/src/components/UI/organisms/Footer/Footer.tsx
  client/src/components/UI/organisms/LectureReview/LectureReview.tsx
  client/src/components/UI/organisms/LectureReview/LectureReviewContainer.tsx
  client/src/components/UI/organisms/index.ts
  client/src/components/pages/MainPage.tsx
  client/src/components/pages/ReviewPage.tsx
Labels: 💀 Bug, 🚧 Refactor

#91 불필요한 패키지 삭제
  client/package.json
  client/yarn.lock
Labels: ⚙ Setting, 🎨 FE

#92 Button 컴포넌트 사이즈 조절이 가능하도록 수정
  client/src/__test__/common/utils/unit.test.ts
  client/src/common/utils/index.ts
  client/src/common/utils/unit.ts
  client/src/components/UI/atoms/Button/Button.stories.tsx
  client/src/components/UI/atoms/Button/Button.tsx
  client/src/components/UI/molecules/HeaderAuthSection/HeaderAuthSectionArea.tsx
  client/src/components/UI/molecules/LectureReviewTitle/LectureReviewTitle.stories.tsx
  client/src/components/UI/molecules/LectureReviewTitle/LectureReviewTitle.tsx
  client/src/components/UI/molecules/TimeTableAddForm/TimeTableAddFormContent.tsx
  client/src/components/UI/molecules/index.ts
  client/src/components/pages/ReviewPage.tsx
Labels: 🎨 FE, 🚧 Refactor

#95 회원가입 API 연동 작업
  client/package.json
  client/schema.json
  client/src/api.d.ts
  client/src/components/UI/molecules/SignUpModalContent/SignUpModalContent.tsx
  client/src/components/UI/organisms/ModalPopup/ModalPopup.tsx
  client/src/components/UI/organisms/ModalPopup/SignUpModalPopup.tsx
  client/src/queries/hello.queries.ts
  client/src/queries/index.ts
  client/src/queries/signup.queries.ts
Labels: 🎨 FE

#100 회원가입 폼 UI 변경 및 기능 구현
  client/src/__test__/common/utils/validator.test.ts
  client/src/common/styles/theme.ts
  client/src/common/utils/validator.ts
  client/src/components/UI/atoms/AlertSnackbar/AlertSnackbar.tsx
  client/src/components/UI/atoms/Button/Button.tsx
  client/src/components/UI/molecules/HeaderAuthSection/HeaderAuthSectionArea.tsx
  client/src/components/UI/molecules/SignUpModalContent/SignUpModalContent.stories.tsx
  client/src/components/UI/molecules/SignUpModalContent/SignUpModalContent.tsx
  client/src/components/UI/organisms/ModalPopup/SignUpModalPopup.tsx
  client/src/stores/SnackbarStore.ts
Labels: 🎨 FE, 👨‍👨‍👦 organism, 👭 molecule

#98 LectureList 리팩토링
  client/src/components/UI/atoms/LectureBox/LectureBox.tsx
  client/src/components/UI/atoms/LectureInfoTitle/LectureInfoTitle.tsx
  client/src/components/UI/molecules/LectureBoxContainer/LectureBoxContainer.tsx
  client/src/components/UI/molecules/LectureInfo/LectureInfo.tsx
  client/src/components/UI/molecules/LectureListContent/LectureListContent.tsx
  client/src/components/UI/molecules/index.ts
  client/src/components/UI/organisms/LectureList/BasketLectureList.tsx
  client/src/components/UI/organisms/LectureList/LectureList.tsx
  client/src/components/UI/organisms/LectureList/SearchedLectureList.tsx
  client/src/components/UI/organisms/index.ts
  client/src/components/pages/MainPage.tsx
  client/src/stores/LectureInfoStore.ts
Labels: 🚧 Refactor

#102 마이페이지 기초 작업
  client/src/components/UI/atoms/MyPageMenu/MyPageMenu.tsx
  client/src/components/UI/atoms/index.ts
  client/src/components/UI/molecules/MyPageMenus/MyPageMenus.tsx
  client/src/components/UI/molecules/index.ts
  client/src/components/UI/organisms/MyPageContentViewer/MyPageContentViewer.tsx
  client/src/components/UI/organisms/index.ts
  client/src/components/pages/MyPage.tsx
  client/src/stores/MyPageStore.ts
  client/src/stores/RootStore.ts
  client/src/stores/index.ts
Labels: 👨‍👩‍👧‍👦 page

#104 로그인 폼 UI 변경 및 로그인 기능 구현
  client/src/common/hooks/index.ts
  client/src/common/hooks/useFetchAsync.ts
  client/src/components/UI/atoms/AlertSnackbar/AlertSnackbar.tsx
  client/src/components/UI/molecules/LoginModalContent/LoginModalContent.stories.tsx
  client/src/components/UI/molecules/LoginModalContent/LoginModalContent.tsx
  client/src/components/UI/organisms/ModalPopup/LoginModalPopup.stories.tsx
  client/src/components/UI/organisms/ModalPopup/LoginModalPopup.tsx
  client/src/components/UI/organisms/ModalPopup/ModalPopup.tsx
  client/src/setupProxy.js
Labels: 🎨 FE, 👨‍👨‍👦 organism, 👭 molecule

#106 사용자 프로필 UI 컴포넌트 제작
  client/src/components/UI/molecules/UserProfile/UserProfile.stories.tsx
  client/src/components/UI/molecules/UserProfile/UserProfile.tsx
  client/src/components/UI/molecules/index.ts
Labels: 🎨 FE, 👭 molecule

#110 로그인, 회원가입 모달 폼 코드 리팩토링
  src/common/hooks/index.ts
  src/common/hooks/useInputForm.ts
  src/components/UI/molecules/LoginModalContent/LoginModalContent.stories.tsx
  src/components/UI/molecules/LoginModalContent/LoginModalContent.tsx
  src/components/UI/molecules/SignUpModalContent/SignUpModalContent.stories.tsx
  src/components/UI/molecules/SignUpModalContent/SignUpModalContent.tsx
  src/components/UI/organisms/ModalPopup/LoginModalPopup.tsx
  src/components/UI/organisms/ModalPopup/SignUpModalPopup.tsx
Labels: 🎨 FE, 🚧 Refactor

#120 Heroku 서버 Proxy 설정 변경
  static.json
Labels: ⚙ Setting, 🎨 FE, 🏕 DevOps

#115 검색 기능 구현
  src/components/Skeleton/LectureListSkeleton/LectureListSkeleton.tsx
  src/components/UI/molecules/LectureBoxContainer/LectureBoxContainer.tsx
  src/components/UI/molecules/LectureSearchFilter/LectureSearchFilterMenu.tsx
  src/components/UI/molecules/SearchBar/SearchBar.tsx
  src/components/UI/organisms/LectureList/SearchedLectureList.tsx
  src/stores/LectureInfoStore.ts
Labels: 🛠 feature

#121 초기화 및 기타 작업
  src/components/Skeleton/LectureListSkeleton/LectureListSkeleton.tsx
  src/components/UI/atoms/LectureInfoTitle/LectureInfoTitle.tsx
  src/components/UI/atoms/SelectMenu/SelectMenu.tsx
  src/components/UI/atoms/TimeSelectMenu/TimeSelectMenu.tsx
  src/components/UI/molecules/LectureInfo/LectureInfo.tsx
  src/components/UI/molecules/LectureListContent/LectureListContent.tsx
  src/components/UI/molecules/LectureSearchFilter/LectureSearchFilter.tsx
  src/components/UI/molecules/LectureSearchFilter/LectureSearchFilterMenu.tsx
  src/components/UI/molecules/ReviewSearchSection/ReviewSearchSection.tsx
  src/components/UI/molecules/TimeTableAddForm/TimeTableAddForm.tsx
  src/components/UI/molecules/TimeTableAddForm/TimeTableAddFormContent.tsx
  src/components/UI/organisms/LectureList/SearchedLectureList.tsx
  src/components/UI/organisms/LectureReviewWriteForm/LectureReviewWriteForm.tsx
  src/components/pages/MainPage.tsx
Labels: 👨‍👨‍👦 organism, 👭 molecule, 🛠 feature

#123 장바구니 시간표 추가 기능 및 시간표 추가시 제약 조건 추가
  src/components/UI/atoms/AlertSnackbar/AlertSnackbar.tsx
  src/components/UI/atoms/TimeSelectMenu/TimeSelectMenu.tsx
  src/components/UI/molecules/LectureSearchFilter/LectureSearchFilterMenu.tsx
  src/components/UI/molecules/TimeTableAddForm/TimeTableAddForm.tsx
  src/components/UI/molecules/TimeTableAddForm/TimeTableAddFormContent.tsx
  src/components/UI/organisms/LectureList/SearchedLectureList.tsx
  src/stores/TimeTableStore.ts
Labels: 👭 molecule, 🛠 feature

#122 로그인 정보확인 API 연동 및 회원가입 폼 이메일, 닉네임 중복체크 기능 구현
  src/api.d.ts
  src/components/UI/atoms/AlertSnackbar/AlertSnackbar.tsx
  src/components/UI/atoms/HeaderMenu/HeaderMenu.tsx
  src/components/UI/atoms/LectureBox/LectureBox.tsx
  src/components/UI/molecules/HeaderAuthSection/HeaderAuthSection.tsx
  src/components/UI/molecules/HeaderLoginMenu/HeaderLoginMenu.stories.tsx
  src/components/UI/molecules/HeaderLoginMenu/HeaderLoginMenu.tsx
  src/components/UI/molecules/HeaderLoginMenu/HeaderLoginMenuArea.tsx
  src/components/UI/molecules/HeaderNavSection/HeaderNavSection.tsx
  src/components/UI/molecules/SignUpModalContent/SignUpModalContent.tsx
  src/components/UI/molecules/UserProfile/UserProfile.tsx
  src/components/UI/molecules/index.ts
  src/components/UI/organisms/Header/Header.tsx
  src/components/UI/organisms/LectureList/BasketLectureList.tsx
  src/components/UI/organisms/LectureList/SearchedLectureList.tsx
  src/components/UI/organisms/LectureReview/LectureReviewContainer.tsx
  src/components/UI/organisms/ModalPopup/LoginModalPopup.tsx
  src/components/UI/organisms/ModalPopup/ModalPopup.tsx
  src/components/UI/organisms/ModalPopup/SignUpModalPopup.tsx
  src/components/UI/organisms/TimeTableMenu/TimeTableMenu.tsx
  src/queries/index.ts
  src/queries/memberDuplicatedByEmail.queries.ts
  src/queries/memberDuplicatedByNickname.queries.ts
  src/queries/myMemberInfo.queries.ts
  src/stores/ModalStore.ts
  src/stores/SnackbarStore.ts
Labels: 🎨 FE, 🚧 Refactor, 🛠 feature

#124 회원가입 폼 중복체크 로직 수정 작업
  src/common/hooks/useInputForm.ts
  src/components/UI/atoms/AlertSnackbar/AlertSnackbar.tsx
  src/components/UI/molecules/SignUpModalContent/SignUpModalContent.tsx
  src/components/UI/organisms/ModalPopup/SignUpModalPopup.tsx
  src/stores/SnackbarStore.ts
Labels: 💀 Bug, 🚧 Refactor

#127 강의 목록 검색 Throttling 적용
  src/common/utils/index.ts
  src/common/utils/throttle.ts
  src/components/UI/molecules/ReviewSearchSection/ReviewSearchSection.tsx
  src/components/UI/molecules/SearchBar/LectureSearchBar.tsx
  src/components/UI/molecules/SearchBar/ReviewSearchBar.tsx
  src/components/UI/molecules/SearchBar/SearchBar.stories.tsx
  src/components/UI/molecules/SearchBar/SearchBar.tsx
  src/components/UI/molecules/index.ts
  src/components/UI/organisms/ModalPopup/SignUpModalPopup.tsx
  src/components/pages/MainPage.tsx
  src/reset.css
  src/stores/LectureInfoStore.ts
Labels: 🎨 FE, 🚧 Refactor, 🛠 feature

#128 비밀번호 찾기 모달 폼 제작
  src/components/UI/molecules/FindModalContent/FindModalContent.stories.tsx
  src/components/UI/molecules/FindModalContent/FindModalContent.tsx
  src/components/UI/molecules/HeaderLoginMenu/HeaderLoginMenu.tsx
  src/components/UI/molecules/HeaderLoginMenu/HeaderLoginMenuArea.tsx
  src/components/UI/molecules/index.ts
  src/components/UI/organisms/ModalPopup/FindModalPopup.tsx
  src/components/UI/organisms/ModalPopup/ModalPopup.tsx
  src/stores/ModalStore.ts
Labels: 🎨 FE, 👭 molecule, 🚧 Refactor, 🛠 feature

#131 (Time)SelectMenu, LectureInfoStore, TypeCheck 관련 코드 리팩토링
  src/common/hooks/index.ts
  src/common/hooks/useReactiveVars.ts
  src/common/hooks/useSelectMenu.ts
  src/common/hooks/useTimeSelectMenu.ts
  src/common/utils/typeCheck.ts
  src/components/UI/atoms/SelectMenu/SelectMenu.tsx
  src/components/UI/atoms/TimeSelectMenu/TimeSelectMenu.tsx
  src/components/UI/molecules/LectureBoxContainer/LectureBoxContainer.tsx
  src/components/UI/molecules/LectureSearchFilter/LectureSearchFilterMenu.tsx
  src/components/UI/molecules/ReviewSearchSection/ReviewSearchSection.tsx
  src/components/UI/molecules/TimeTableAddForm/TimeTableAddForm.tsx
  src/components/UI/molecules/TimeTableAddForm/TimeTableAddFormContent.tsx
  src/components/UI/molecules/Timetable/Timetable.tsx
  src/components/UI/organisms/LectureList/BasketLectureList.tsx
  src/components/UI/organisms/LectureList/SearchedLectureList.tsx
  src/components/UI/organisms/LectureReviewWriteForm/LectureReviewWriteForm.tsx
  src/stores/LectureInfoStore.ts
  src/stores/index.ts
Labels: 🎨 FE, 💀 Bug, 🚧 Refactor
